name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Lint with ruff
      run: |
        ruff check opengov_earlyfrench tests
    
    - name: Format check with black
      run: |
        black --check opengov_earlyfrench tests
    
    - name: Type check with mypy
      run: |
        mypy opengov_earlyfrench || true
    
    - name: Test with pytest
      run: |
        pytest tests/ --cov=opengov_earlyfrench --cov-report=xml --cov-report=term-missing -v
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t opengov-earlyfrench:latest .
    
    - name: Test Docker image
      run: |
        docker run --rm opengov-earlyfrench:latest python -c "import opengov_earlyfrench; print(opengov_earlyfrench.__version__)"

